### ISSUE TITLE
Add more commands

### ISSUE THREAD

**Issue by k911** [k911/swoole-bundle#2]
- [x] `swoole:server:start` - Start swoole server in background #8 
- [x] `swoole:server:stop` #8 
- [x] `swoole:server:reload` #8 
- [ ] `swoole:server:status`
